"use client";
import { useActionState } from "react";
import type { SeasonSetupDraft } from "@/domain";
import { Button, Card } from "@/components/ui";
import { addConstraint, addGoal, addOutcome, addPriority, editGoal, editOutcome, editPriority, removeConstraint, removeGoal, removeOutcome, removePriority, reviewSetup, saveFoundation, togglePriority, type FormActionState } from "@/server/planning/setup-actions";
const idleState: FormActionState = { status: "idle" };

function Feedback({ state }: { state: FormActionState }) { return state.status === "error" ? <p className="form-error" role="alert">{state.message}</p> : state.message ? <p className="form-success" role="status">{state.message}</p> : null; }
function Submit({ children }: { children: React.ReactNode }) { return <Button type="submit" tone="primary">{children}</Button>; }

export function SetupEditor({ draft }: { draft: SeasonSetupDraft }) {
  const [foundation, foundationAction, foundationPending] = useActionState(saveFoundation, idleState);
  const [priority, priorityAction, priorityPending] = useActionState(addPriority, idleState);
  const [constraint, constraintAction, constraintPending] = useActionState(addConstraint, idleState);
  const [goal, goalAction, goalPending] = useActionState(addGoal, idleState);
  return <div className="setup-layout">
    <header className="setup-progress"><p className="eyebrow">Guided season setup</p><h1>{draft.title || "New season"}</h1><p>Step through the foundation, priorities, goals, and outcomes. Everything here remains a proposal until you explicitly confirm.</p><nav aria-label="Setup steps"><span className="is-current">1 Foundation</span><span>2 Priorities</span><span>3 Goals</span><span>4 Outcomes</span><span>5 Review</span></nav></header>
    <Card><h2>Foundation</h2><p className="muted">Give this season a name, a purpose, and a realistic window.</p><form action={foundationAction} className="setup-form">
      <input type="hidden" name="setupDraftId" value={draft.id} />
      <label>Season title<input name="title" defaultValue={draft.title} required /></label>
      <label>Intent<textarea name="intent" defaultValue={draft.intent ?? ""} required rows={3} /></label>
      <div className="form-grid"><label>Start date<input type="date" name="startDate" defaultValue={draft.startDate ?? ""} required /></label><label>End date<input type="date" name="endDate" defaultValue={draft.endDate ?? ""} required /></label></div>
      <div className="form-actions"><Submit>{foundationPending ? "Saving…" : "Save foundation"}</Submit></div><Feedback state={foundation} />
    </form></Card>
    <Card><h2>Priorities</h2><p className="muted">Brainstorm freely. Select the ideas that should influence your goals; not every idea needs to become a goal.</p><div className="setup-list">{draft.priorityIdeas.map(item => <PriorityEditor key={item.id} draft={draft} item={item} />)}</div><form action={priorityAction} className="inline-form"><input type="hidden" name="setupDraftId" value={draft.id} /><label className="sr-only" htmlFor="priority-text">New priority idea</label><input id="priority-text" name="text" placeholder="Add a priority idea" required /><Submit>{priorityPending ? "Adding…" : "Add"}</Submit></form><Feedback state={priority} /></Card>
    <Card><h2>Constraints and capacity</h2><p className="muted">Optional notes about time, energy, resources, or boundaries.</p><div className="setup-list">{draft.constraints.map(item => <div className="setup-row" key={item.id}><span>{item.text}</span><form action={removeConstraint}><input type="hidden" name="setupDraftId" value={draft.id} /><input type="hidden" name="itemId" value={item.id} /><Button type="submit">Remove</Button></form></div>)}</div><form action={constraintAction} className="inline-form"><input type="hidden" name="setupDraftId" value={draft.id} /><label className="sr-only" htmlFor="constraint-text">New constraint</label><input id="constraint-text" name="text" placeholder="Add a constraint" required /><Submit>{constraintPending ? "Adding…" : "Add"}</Submit></form><Feedback state={constraint} /></Card>
    <Card><h2>Goals</h2><p className="muted">Goals are open-ended and user-authored. No category or template is required.</p><div className="setup-list">{draft.proposedGoals.map(item => <GoalEditor key={item.id} draft={draft} goal={item} />)}</div><form action={goalAction} className="inline-form"><input type="hidden" name="setupDraftId" value={draft.id} /><label className="sr-only" htmlFor="goal-text">New goal</label><input id="goal-text" name="text" placeholder="Add a proposed goal" required /><Submit>{goalPending ? "Adding…" : "Add goal"}</Submit></form><Feedback state={goal} /></Card>
    <Card className="setup-next"><h2>Ready to review?</h2><p className="muted">Review will show blockers and warnings before you confirm. Confirmation locks the proposal but does not create or activate a season.</p><form action={reviewSetup}><input type="hidden" name="setupDraftId" value={draft.id} /><Submit>Review setup</Submit></form></Card>
  </div>;
}

function GoalEditor({ draft, goal }: { draft: SeasonSetupDraft; goal: SeasonSetupDraft["proposedGoals"][number] }) {
  const [edit, editAction, pending] = useActionState(editGoal, idleState);
  const [outcome, outcomeAction, outcomePending] = useActionState(addOutcome, idleState);
  return <section className="goal-editor"><div className="goal-editor__header"><h3>{goal.text}</h3><form action={removeGoal}><input type="hidden" name="setupDraftId" value={draft.id} /><input type="hidden" name="goalId" value={goal.id} /><Button type="submit">Remove goal</Button></form></div><form action={editAction} className="setup-form compact"><input type="hidden" name="setupDraftId" value={draft.id} /><input type="hidden" name="goalId" value={goal.id} /><label>Goal title<input name="text" defaultValue={goal.text} required /></label><Submit>{pending ? "Saving…" : "Save goal"}</Submit><Feedback state={edit} /></form><div className="outcome-list"><h4>Measurable outcomes</h4>{draft.proposedOutcomes.filter(x => goal.outcomeIds.includes(x.id)).map(outcome => <OutcomeEditor key={outcome.id} draft={draft} outcome={outcome} />)}</div><form action={outcomeAction} className="outcome-form"><input type="hidden" name="setupDraftId" value={draft.id} /><input type="hidden" name="goalId" value={goal.id} /><label>Outcome<input name="text" required placeholder="What will be true?" /></label><label>Type<select name="type" defaultValue="boolean"><option value="boolean">Boolean</option><option value="numeric">Numeric target</option><option value="percentage">Percentage</option><option value="count">Count</option></select></label><label>Target (not needed for boolean)<input name="targetValue" type="number" min="1" step="1" /></label><label>Unit (optional)<input name="unit" placeholder="hours, books, %" /></label><Submit>{outcomePending ? "Adding…" : "Add outcome"}</Submit><Feedback state={outcome} /></form></section>;
}

function PriorityEditor({ draft, item }: { draft: SeasonSetupDraft; item: SeasonSetupDraft["priorityIdeas"][number] }) { const [edit, editAction, pending] = useActionState(editPriority, idleState); return <div className="setup-row"><label className="checkbox-row"><input type="checkbox" checked={item.selected ?? false} onChange={e => { const f = new FormData(); f.set("setupDraftId", draft.id); f.set("itemId", item.id); f.set("selected", String(e.target.checked)); void togglePriority(f); }} /><span>{item.text}</span></label><form action={editAction} className="inline-form"><input type="hidden" name="setupDraftId" value={draft.id} /><input type="hidden" name="itemId" value={item.id} /><label className="sr-only">Edit priority</label><input name="text" defaultValue={item.text} /><Submit>{pending ? "Saving…" : "Save"}</Submit><Feedback state={edit} /></form><form action={removePriority}><input type="hidden" name="setupDraftId" value={draft.id} /><input type="hidden" name="itemId" value={item.id} /><Button type="submit">Remove</Button></form></div>; }

function OutcomeEditor({ draft, outcome }: { draft: SeasonSetupDraft; outcome: SeasonSetupDraft["proposedOutcomes"][number] }) {
  const [edit, editAction, pending] = useActionState(editOutcome, idleState);
  return <div className="outcome-editor"><form action={editAction} className="outcome-form compact"><input type="hidden" name="setupDraftId" value={draft.id} /><input type="hidden" name="outcomeId" value={outcome.id} /><label>Outcome<input name="text" defaultValue={outcome.text} required /></label><label>Type<select name="type" defaultValue={outcome.type ?? (typeof outcome.targetValue === "boolean" ? "boolean" : "numeric")}><option value="boolean">Boolean</option><option value="numeric">Numeric target</option><option value="percentage">Percentage</option><option value="count">Count</option></select></label><label>Target<input name="targetValue" type="number" min="1" step="1" defaultValue={typeof outcome.targetValue === "number" ? outcome.targetValue : ""} /></label><label>Unit<input name="unit" defaultValue={outcome.unit ?? ""} /></label><Submit>{pending ? "Saving…" : "Save outcome"}</Submit><Feedback state={edit} /></form><form action={removeOutcome}><input type="hidden" name="setupDraftId" value={draft.id} /><input type="hidden" name="outcomeId" value={outcome.id} /><Button type="submit">Remove outcome</Button></form></div>;
}
