import test from "node:test";import assert from "node:assert/strict";
import type { Goal, Milestone, Outcome, Season, SeasonSetupDraft } from "../src/domain";
import type { Clock, IdGenerator } from "../src/application";import { executeSeasonSetupConversion } from "../src/application";
import type { GoalRepository, MilestoneRepository, OutcomeRepository, PlanningTransactionRunner, SeasonRepository, SeasonSetupDraftRepository, TransactionContext } from "../src/persistence";
import { persistenceFailure, PostgresPlanningUnitOfWork, PostgresSeasonReviewRepository, PostgresSeasonSetupDraftRepository, PostgresTransactionRunner } from "../src/persistence";
import { applyMigrations,cleanDatabase,createRealTestDatabase } from "./support/postgres-test-database";

const now="2026-07-11T12:00:00.000Z";const clock:Clock={now:()=>now,today:()=>"2026-07-11"};
class PrefixIds implements IdGenerator {#s=0;#g=0;#o=0;#m=0;constructor(private readonly prefix:string){}nextSeasonId(){return `${this.prefix}-season-${++this.#s}`;}nextGoalId(){return `${this.prefix}-goal-${++this.#g}`;}nextOutcomeId(){return `${this.prefix}-outcome-${++this.#o}`;}nextMilestoneId(){return `${this.prefix}-milestone-${++this.#m}`;}}
const draft=(id="setup-real"):SeasonSetupDraft=>({id,status:"confirmed",title:"Real PostgreSQL",intent:"Prove transactions",startDate:"2026-08-01",endDate:"2026-10-31",priorityIdeas:[],proposedGoals:[{id:"pg",text:"Ship safely",source:"user",outcomeIds:["po"]}],proposedOutcomes:[{id:"po",text:"One release",source:"user",targetValue:1}],supportingStructures:[{id:"pm",text:"Migration verified",source:"user",kind:"milestone",proposedGoalId:"pg"}],constraints:[],openQuestions:[],carryForwardContext:[],createdAt:now,updatedAt:now,confirmedAt:now});
const deferred=()=>{let resolve!:()=>void;const promise=new Promise<void>(r=>resolve=r);return{promise,resolve};};
class LockObservedRunner implements PlanningTransactionRunner {constructor(private readonly inner:PlanningTransactionRunner,private readonly before:boolean,private readonly reached:{resolve():void},private readonly release?:Promise<void>){}runInTransaction<T>(operation:(context:TransactionContext)=>Promise<import("../src/persistence").PersistenceResult<T>>){return this.inner.runInTransaction(context=>operation({...context,workflow:{...context.workflow,lockSetupDraft:async id=>{if(this.before)this.reached.resolve();const result=await context.workflow.lockSetupDraft(id);if(!this.before)this.reached.resolve();if(this.release)await this.release;return result;}}}));}}
type FailureStage="season"|"goal"|"outcome"|"milestone"|"workflow";
class FailingRunner implements PlanningTransactionRunner {constructor(private readonly inner:PlanningTransactionRunner,private readonly stage:FailureStage){}runInTransaction<T>(operation:(context:TransactionContext)=>Promise<import("../src/persistence").PersistenceResult<T>>){return this.inner.runInTransaction(context=>{const fail=()=>Promise.resolve(persistenceFailure<never>({code:"storage_failure",message:"Injected test failure."}));const planning={seasons:this.stage==="season"?{...context.planning.seasons,save:fail as SeasonRepository["save"]}:context.planning.seasons,goals:this.stage==="goal"?{...context.planning.goals,save:fail as GoalRepository["save"]}:context.planning.goals,outcomes:this.stage==="outcome"?{...context.planning.outcomes,save:fail as OutcomeRepository["save"]}:context.planning.outcomes,milestones:this.stage==="milestone"?{...context.planning.milestones,save:fail as MilestoneRepository["save"]}:context.planning.milestones};const original=context.workflow.setupDrafts;const setupDrafts=this.stage==="workflow"?{findById:(id:string)=>original.findById(id),list:()=>original.list(),save:async(v:SeasonSetupDraft)=>v.status==="converted"?fail():original.save(v)} as SeasonSetupDraftRepository:original;return operation({...context,planning,workflow:{...context.workflow,setupDrafts}});});}}

test("real PostgreSQL applies migrations idempotently and supports repositories",async()=>{const c=await createRealTestDatabase();try{await applyMigrations(c.database);await applyMigrations(c.database);await cleanDatabase(c.database);const planning=new PostgresPlanningUnitOfWork(c.database),drafts=new PostgresSeasonSetupDraftRepository(c.database),reviews=new PostgresSeasonReviewRepository(c.database);const season:Season={id:"s",name:"Season",dates:{startDate:"2026-01-01",endDate:"2026-03-31"},status:"draft",createdAt:now,updatedAt:now};assert.equal((await planning.seasons.save(season)).ok,true);assert.equal((await planning.seasons.findById("missing")).ok,true);const goal:Goal={id:"g",seasonId:"s",title:"Goal",status:"draft",createdAt:now,updatedAt:now};await planning.goals.save(goal);const outcome:Outcome={id:"o",goalId:"g",description:"Outcome",type:"count",targetValue:1};await planning.outcomes.save(outcome);const milestone:Milestone={id:"m",goalId:"g",title:"Milestone",status:"not_started"};await planning.milestones.save(milestone);assert.equal((await planning.goals.listBySeasonId("s")).ok,true);assert.equal((await planning.outcomes.listByGoalId("g")).ok,true);assert.equal((await planning.milestones.listByGoalId("g")).ok,true);await drafts.save(draft("setup-repo"));assert.equal((await drafts.findById("setup-repo")).ok,true);assert.equal((await reviews.findById("missing")).ok,true);const duplicate=await planning.seasons.save({...season,name:"updated"});assert.equal(duplicate.ok,true);const fk=await planning.goals.save({...goal,id:"orphan",seasonId:"absent"});assert.equal(fk.ok,false);}finally{await c.close();}});
test("real PostgreSQL rolls back every conversion write stage",async()=>{const c=await createRealTestDatabase();try{await applyMigrations(c.database);const base=new PostgresTransactionRunner(c.database),planning=new PostgresPlanningUnitOfWork(c.database),drafts=new PostgresSeasonSetupDraftRepository(c.database);for(const stage of ["season","goal","outcome","milestone","workflow"] as const){await cleanDatabase(c.database);const value=draft(`setup-${stage}`);await drafts.save(value);const result=await executeSeasonSetupConversion({transactions:new FailingRunner(base,stage),clock,ids:new PrefixIds(stage)},value.id);assert.equal(result.ok,false,stage);const seasons=await planning.seasons.list();assert.equal(seasons.ok,true);if(seasons.ok)assert.equal(seasons.value.length,0,stage);const stored=await drafts.findById(value.id);assert.equal(stored.ok,true);if(stored.ok){assert.equal(stored.value?.status,"confirmed",stage);assert.equal(stored.value?.targetSeasonId,undefined,stage);}}await cleanDatabase(c.database);const retry=draft("setup-retry");await drafts.save(retry);assert.equal((await executeSeasonSetupConversion({transactions:base,clock,ids:new PrefixIds("retry")},retry.id)).ok,true);}finally{await c.close();}});
test("two independent PostgreSQL connections allow exactly one conversion",async()=>{const seed=await createRealTestDatabase(),a=await createRealTestDatabase(),b=await createRealTestDatabase();try{await applyMigrations(seed.database);await cleanDatabase(seed.database);const drafts=new PostgresSeasonSetupDraftRepository(seed.database),planning=new PostgresPlanningUnitOfWork(seed.database),value=draft();await drafts.save(value);const firstLocked=deferred(),releaseFirst=deferred(),secondAttempted=deferred();const firstRunner=new LockObservedRunner(new PostgresTransactionRunner(a.database),false,firstLocked,releaseFirst.promise);const secondRunner=new LockObservedRunner(new PostgresTransactionRunner(b.database),true,secondAttempted);const first=executeSeasonSetupConversion({transactions:firstRunner,clock,ids:new PrefixIds("first")},value.id);await firstLocked.promise;const second=executeSeasonSetupConversion({transactions:secondRunner,clock,ids:new PrefixIds("second")},value.id);await secondAttempted.promise;releaseFirst.resolve();const results=await Promise.all([first,second]);assert.equal(results.filter(x=>x.ok).length,1);assert.equal(results.filter(x=>!x.ok).length,1);const seasons=await planning.seasons.list();assert.equal(seasons.ok,true);if(!seasons.ok)return;assert.equal(seasons.value.length,1);const goals=await planning.goals.listBySeasonId(seasons.value[0]!.id);assert.equal(goals.ok,true);if(!goals.ok)return;assert.equal(goals.value.length,1);const outcomes=await planning.outcomes.listByGoalId(goals.value[0]!.id),milestones=await planning.milestones.listByGoalId(goals.value[0]!.id);assert.equal(outcomes.ok,true);assert.equal(milestones.ok,true);if(outcomes.ok)assert.equal(outcomes.value.length,1);if(milestones.ok)assert.equal(milestones.value.length,1);const stored=await drafts.findById(value.id);assert.equal(stored.ok,true);if(stored.ok)assert.equal(stored.value?.targetSeasonId,seasons.value[0]!.id);assert.equal((await executeSeasonSetupConversion({transactions:new PostgresTransactionRunner(seed.database),clock,ids:new PrefixIds("third")},value.id)).ok,false);}finally{await Promise.all([seed.close(),a.close(),b.close()]);}});
