"use server";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { addProposedGoal, addProposedOutcome, addSetupItem, confirmSeasonSetup, createSeasonSetupDraft, executeSeasonSetupConversion, markSetupReadyForReview, removeProposedGoal, removeProposedOutcome, removeSetupItem, toggleSetupItem, updateProposedGoal, updateProposedOutcome, updateSeasonSetupDetails, updateSetupItem } from "@/application";
import { planningContext } from "./dependencies";

export type FormActionState = { status: "idle" | "success" | "error"; message?: string; fieldErrors?: Record<string, string[]> };
const idleState: FormActionState = { status: "idle" };
const text = (form: FormData, key: string) => String(form.get(key) ?? "").trim();
const optional = (form: FormData, key: string) => { const value = String(form.get(key) ?? "").trim(); return value || undefined; };
const stateFrom = (result: { ok: boolean; errors?: { message: string; field?: string }[] }): FormActionState => result.ok ? { status: "success" } : { status: "error", message: result.errors?.[0]?.message ?? "We could not save that yet.", fieldErrors: Object.fromEntries((result.errors ?? []).filter(x => x.field).map(x => [x.field!, [x.message]])) };
const id = (form: FormData) => text(form, "setupDraftId");
const refresh = (draftId: string) => { revalidatePath("/season"); revalidatePath(`/season/setup/${draftId}`); revalidatePath(`/season/setup/${draftId}/review`); };

export async function startSeasonSetup(_prev: FormActionState, form: FormData): Promise<FormActionState> { const ctx = await planningContext(); const result = await createSeasonSetupDraft(ctx.workflow, { title: text(form, "title") || "Untitled season" }); if (!result.ok) return stateFrom(result); redirect(`/season/setup/${result.value.id}`); }
export async function startSeasonSetupDirect(form: FormData): Promise<void> { await startSeasonSetup(idleState, form); }
export async function saveFoundation(_prev: FormActionState, form: FormData): Promise<FormActionState> { const ctx = await planningContext(); const result = await updateSeasonSetupDetails(ctx.workflow, { draftId: id(form), title: text(form, "title"), intent: text(form, "intent"), startDate: text(form, "startDate"), endDate: text(form, "endDate") }); if (result.ok) { refresh(id(form)); return { status: "success", message: "Foundation saved." }; } return stateFrom(result); }
export async function addPriority(_prev: FormActionState, form: FormData): Promise<FormActionState> { const ctx = await planningContext(); const result = await addSetupItem(ctx.workflow, { draftId: id(form), collection: "priorityIdeas", text: text(form, "text") }); if (result.ok) refresh(id(form)); return result.ok ? { status: "success", message: "Priority added." } : stateFrom(result); }
export async function removePriority(form: FormData) { const ctx = await planningContext(); const result = await removeSetupItem(ctx.workflow, { draftId: id(form), collection: "priorityIdeas", itemId: text(form, "itemId") }); if (result.ok) refresh(id(form)); }
export async function removeConstraint(form: FormData) { const ctx = await planningContext(); const result = await removeSetupItem(ctx.workflow, { draftId: id(form), collection: "constraints", itemId: text(form, "itemId") }); if (result.ok) refresh(id(form)); }
export async function togglePriority(form: FormData) { const ctx = await planningContext(); const result = await toggleSetupItem(ctx.workflow, { draftId: id(form), itemId: text(form, "itemId"), selected: text(form, "selected") === "true" }); if (result.ok) refresh(id(form)); }
export async function editPriority(_prev: FormActionState, form: FormData): Promise<FormActionState> { const ctx = await planningContext(); const result = await updateSetupItem(ctx.workflow, { draftId: id(form), collection: "priorityIdeas", itemId: text(form, "itemId"), text: text(form, "text") }); if (result.ok) refresh(id(form)); return result.ok ? { status: "success", message: "Priority updated." } : stateFrom(result); }
export async function addConstraint(_prev: FormActionState, form: FormData): Promise<FormActionState> { const ctx = await planningContext(); const result = await addSetupItem(ctx.workflow, { draftId: id(form), collection: "constraints", text: text(form, "text") }); if (result.ok) refresh(id(form)); return result.ok ? { status: "success", message: "Constraint saved." } : stateFrom(result); }
export async function addGoal(_prev: FormActionState, form: FormData): Promise<FormActionState> { const ctx = await planningContext(); const result = await addProposedGoal(ctx.workflow, { draftId: id(form), text: text(form, "text") }); if (result.ok) refresh(id(form)); return result.ok ? { status: "success", message: "Goal added." } : stateFrom(result); }
export async function editGoal(_prev: FormActionState, form: FormData): Promise<FormActionState> { const ctx = await planningContext(); const result = await updateProposedGoal(ctx.workflow, { draftId: id(form), goalId: text(form, "goalId"), text: text(form, "text") }); if (result.ok) refresh(id(form)); return result.ok ? { status: "success", message: "Goal updated." } : stateFrom(result); }
export async function removeGoal(form: FormData) { const ctx = await planningContext(); const result = await removeProposedGoal(ctx.workflow, { draftId: id(form), goalId: text(form, "goalId") }); if (result.ok) refresh(id(form)); }
const outcomeInput = (form: FormData) => { const type = text(form, "type") as "boolean" | "numeric" | "percentage" | "count"; const raw = optional(form, "targetValue"); if (type === "boolean") return { type, targetValue: true as const }; if (raw === undefined) return { type, targetValue: undefined }; const value = Number(raw); if (!Number.isFinite(value) || value <= 0 || (type === "count" && !Number.isInteger(value))) return null; return { type, targetValue: value }; };
export async function addOutcome(_prev: FormActionState, form: FormData): Promise<FormActionState> { const parsed = outcomeInput(form); if (!parsed) return { status: "error", message: "Enter a positive valid target; count targets must be whole numbers." }; const ctx = await planningContext(); const result = await addProposedOutcome(ctx.workflow, { draftId: id(form), goalId: text(form, "goalId"), text: text(form, "text"), ...parsed, unit: optional(form, "unit") }); if (result.ok) refresh(id(form)); return result.ok ? { status: "success", message: "Outcome added." } : stateFrom(result); }
export async function editOutcome(_prev: FormActionState, form: FormData): Promise<FormActionState> { const parsed = outcomeInput(form); if (!parsed) return { status: "error", message: "Enter a positive valid target; count targets must be whole numbers." }; const ctx = await planningContext(); const result = await updateProposedOutcome(ctx.workflow, { draftId: id(form), outcomeId: text(form, "outcomeId"), text: text(form, "text"), ...parsed, unit: optional(form, "unit") }); if (result.ok) refresh(id(form)); return result.ok ? { status: "success", message: "Outcome updated." } : stateFrom(result); }
export async function removeOutcome(form: FormData) { const ctx = await planningContext(); const result = await removeProposedOutcome(ctx.workflow, { draftId: id(form), outcomeId: text(form, "outcomeId") }); if (result.ok) refresh(id(form)); }
export async function reviewSetup(form: FormData) { const ctx = await planningContext(); const result = await markSetupReadyForReview(ctx.workflow, id(form)); if (!result.ok) return; refresh(id(form)); redirect(`/season/setup/${id(form)}/review`); }
export async function confirmSetup(form: FormData) { const ctx = await planningContext(); const result = await confirmSeasonSetup(ctx.workflow, id(form)); if (!result.ok) return; refresh(id(form)); redirect(`/season/setup/${id(form)}/complete`); }
export async function convertSetup(form: FormData) { const ctx = await planningContext(); const result = await executeSeasonSetupConversion(ctx.conversion, id(form)); if (!result.ok) return; revalidatePath("/season"); redirect(`/season/${result.value.season.id}`); }
