import type { SeasonReview, SeasonReviewSummaryProposal } from "../../domain";
import { applicationFailure, applicationSuccess, mapPersistenceErrors, notFound, type ApplicationResult } from "../errors";
import type { SeasonWorkflowDependencies } from "./contracts";
import type { SeasonReviewAssistantRequest } from "../assistant";
async function load(deps:SeasonWorkflowDependencies,id:string):Promise<ApplicationResult<SeasonReview>>{const r=await deps.reviews.findById(id);if(!r.ok)return mapPersistenceErrors(r.errors);return r.value?applicationSuccess(r.value):notFound("Season review",id);}
async function save(deps:SeasonWorkflowDependencies,v:SeasonReview):Promise<ApplicationResult<SeasonReview>>{const r=await deps.reviews.save(v);return r.ok?applicationSuccess(r.value):mapPersistenceErrors(r.errors);}
export async function createSeasonReview(deps:SeasonWorkflowDependencies,seasonId:string):Promise<ApplicationResult<SeasonReview>>{const s=await deps.seasons.findById(seasonId);if(!s.ok)return mapPersistenceErrors(s.errors);if(!s.value)return notFound("Season",seasonId);if(s.value.status!=="completed"&&!(s.value.status==="archived"&&s.value.completedAt))return applicationFailure({code:"invalid_transition",message:"Only completed seasons can be reviewed."});const existing=await deps.reviews.findBySeasonId(seasonId);if(!existing.ok)return mapPersistenceErrors(existing.errors);if(existing.value)return applicationFailure({code:"conflict",message:"A review already exists for this season."});const now=deps.clock.now();return save(deps,{id:deps.ids.nextSeasonReviewId(),seasonId,status:"draft",userContent:{highlights:"",challenges:"",lessons:"",nextSeasonConsiderations:""},approvedCarryForwardInsights:[],createdAt:now,updatedAt:now});}
export async function updateSeasonReviewContent(deps:SeasonWorkflowDependencies,input:{reviewId:string;userContent:SeasonReview["userContent"]}):Promise<ApplicationResult<SeasonReview>>{const r=await load(deps,input.reviewId);if(!r.ok)return r;if(r.value.status==="finalized")return applicationFailure({code:"invalid_transition",message:"Finalized reviews are immutable."});return save(deps,{...r.value,userContent:structuredClone(input.userContent),status:"draft",assistantProposal:undefined,updatedAt:deps.clock.now()});}
export async function markReviewReadyForSummary(deps:SeasonWorkflowDependencies,id:string):Promise<ApplicationResult<SeasonReview>>{const r=await load(deps,id);if(!r.ok)return r;if(r.value.status==="finalized")return applicationFailure({code:"invalid_transition",message:"Finalized reviews are immutable."});if(!Object.values(r.value.userContent).some(x=>x.trim()))return applicationFailure({code:"validation_failed",message:"User-authored review content is required."});return save(deps,{...r.value,status:"ready_for_summary",updatedAt:deps.clock.now()});}
export async function buildSeasonReviewAssistantRequest(deps:SeasonWorkflowDependencies,input:{reviewId:string;planningOverview:unknown;availability?:Partial<SeasonReviewAssistantRequest["availability"]>}):Promise<ApplicationResult<SeasonReviewAssistantRequest>>{const r=await load(deps,input.reviewId);if(!r.ok)return r;const s=await deps.seasons.findById(r.value.seasonId);if(!s.ok)return mapPersistenceErrors(s.errors);if(!s.value)return notFound("Season",r.value.seasonId);return applicationSuccess({season:{id:s.value.id,name:s.value.name,status:s.value.status,...(s.value.intent?{intent:s.value.intent.statement}:{})},userContent:structuredClone(r.value.userContent),planningOverview:structuredClone(input.planningOverview),availability:{weeklyReflections:input.availability?.weeklyReflections??"unavailable",dailyCheckIns:input.availability?.dailyCheckIns??"unavailable",completionHistory:input.availability?.completionHistory??"unavailable"}});}
export async function applySeasonReviewProposal(deps:SeasonWorkflowDependencies,input:{reviewId:string;proposal:SeasonReviewSummaryProposal}):Promise<ApplicationResult<SeasonReview>>{const r=await load(deps,input.reviewId);if(!r.ok)return r;if(r.value.status!=="ready_for_summary"&&r.value.status!=="summary_proposed")return applicationFailure({code:"invalid_transition",message:"Review is not ready for an assistant proposal."});return save(deps,{...r.value,assistantProposal:structuredClone(input.proposal),status:"summary_proposed",updatedAt:deps.clock.now()});}
export async function approveCarryForwardInsights(deps:SeasonWorkflowDependencies,input:{reviewId:string;candidateIds:string[]}):Promise<ApplicationResult<SeasonReview>>{const r=await load(deps,input.reviewId);if(!r.ok)return r;if(r.value.status!=="summary_proposed"||!r.value.assistantProposal)return applicationFailure({code:"invalid_transition",message:"A summary proposal is required before approving its insights."});const now=deps.clock.now();const chosen=r.value.assistantProposal.carryForwardCandidates.filter(x=>input.candidateIds.includes(x.id));return save(deps,{...r.value,approvedCarryForwardInsights:chosen.map(x=>({id:deps.ids.nextCarryForwardInsightId(),seasonId:r.value.seasonId,insight:x.insight,sourceType:"season-review",sourceId:r.value.id,approvedAt:now})),updatedAt:now});}
export async function finalizeSeasonReview(deps:SeasonWorkflowDependencies,input:{reviewId:string;confirm:boolean;approvedSummary?:string}):Promise<ApplicationResult<SeasonReview>>{const r=await load(deps,input.reviewId);if(!r.ok)return r;if(!input.confirm)return applicationFailure({code:"validation_failed",message:"Explicit confirmation is required."});if(r.value.status!=="ready_for_summary"&&r.value.status!=="summary_proposed")return applicationFailure({code:"invalid_transition",message:"Review is not ready to finalize."});const summary=input.approvedSummary?.trim()||r.value.assistantProposal?.executiveSummary.trim();if(!summary)return applicationFailure({code:"validation_failed",message:"An approved summary is required.",field:"approvedSummary"});const now=deps.clock.now();return save(deps,{...r.value,status:"finalized",approvedSummary:summary,updatedAt:now,finalizedAt:now});}
