import type { SeasonSetupDraft, SeasonSetupConversionPlan, SourcedWorkflowItem } from "../../domain";
import { applicationFailure, applicationSuccess, mapPersistenceErrors, notFound, type ApplicationResult } from "../errors";
import type { SeasonSetupSuggestion } from "../assistant";
import type { SeasonWorkflowDependencies } from "./contracts";
import { evaluateSetupReadiness } from "./readiness";
const editable=(d:SeasonSetupDraft)=>d.status==="draft"||d.status==="ready_for_review";
async function load(deps:SeasonWorkflowDependencies,id:string):Promise<ApplicationResult<SeasonSetupDraft>>{const r=await deps.setupDrafts.findById(id);if(!r.ok)return mapPersistenceErrors(r.errors);return r.value?applicationSuccess(r.value):notFound("Season setup draft",id);}
async function save(deps:SeasonWorkflowDependencies,d:SeasonSetupDraft):Promise<ApplicationResult<SeasonSetupDraft>>{const r=await deps.setupDrafts.save(d);return r.ok?applicationSuccess(r.value):mapPersistenceErrors(r.errors);}
export async function createSeasonSetupDraft(deps:SeasonWorkflowDependencies,input:{title:string;carryForwardContext?:SeasonSetupDraft["carryForwardContext"]}):Promise<ApplicationResult<SeasonSetupDraft>>{const now=deps.clock.now();return save(deps,{ownerId:deps.ownerId,id:deps.ids.nextSetupDraftId(),status:"draft",title:input.title.trim(),priorityIdeas:[],proposedGoals:[],proposedOutcomes:[],supportingStructures:[],constraints:[],openQuestions:[],carryForwardContext:input.carryForwardContext??[],createdAt:now,updatedAt:now});}
export async function updateSeasonSetupDetails(deps:SeasonWorkflowDependencies,input:{draftId:string;title?:string;startDate?:string;endDate?:string;intent?:string}):Promise<ApplicationResult<SeasonSetupDraft>>{const r=await load(deps,input.draftId);if(!r.ok)return r;if(!editable(r.value))return applicationFailure({code:"invalid_transition",message:"Confirmed or closed setup drafts are immutable."});return save(deps,{...r.value,...(input.title!==undefined?{title:input.title.trim()}:{}),...(input.startDate!==undefined?{startDate:input.startDate}:{}),...(input.endDate!==undefined?{endDate:input.endDate}:{}),...(input.intent!==undefined?{intent:input.intent}:{}),status:"draft",updatedAt:deps.clock.now()});}
export async function addSetupItem(deps:SeasonWorkflowDependencies,input:{draftId:string;collection:"priorityIdeas"|"constraints"|"openQuestions";text:string;source?:"user"|"assistant"}):Promise<ApplicationResult<SeasonSetupDraft>>{const r=await load(deps,input.draftId);if(!r.ok)return r;if(!editable(r.value))return applicationFailure({code:"invalid_transition",message:"Confirmed or closed setup drafts are immutable."});if(!input.text.trim())return applicationFailure({code:"validation_failed",message:"Item text is required.",field:"text"});const item:SourcedWorkflowItem={id:deps.ids.nextWorkflowItemId(),text:input.text.trim(),source:input.source??"user"};return save(deps,{...r.value,[input.collection]:[...r.value[input.collection],item],status:"draft",updatedAt:deps.clock.now()});}
export async function addProposedGoal(deps:SeasonWorkflowDependencies,input:{draftId:string;text:string;source?:"user"|"assistant"}):Promise<ApplicationResult<SeasonSetupDraft>>{const r=await load(deps,input.draftId);if(!r.ok)return r;if(!editable(r.value))return applicationFailure({code:"invalid_transition",message:"Confirmed or closed setup drafts are immutable."});if(!input.text.trim())return applicationFailure({code:"validation_failed",message:"Goal text is required.",field:"text"});return save(deps,{...r.value,proposedGoals:[...r.value.proposedGoals,{id:deps.ids.nextWorkflowItemId(),text:input.text.trim(),source:input.source??"user",outcomeIds:[]}],status:"draft",updatedAt:deps.clock.now()});}
export async function updateProposedGoal(deps:SeasonWorkflowDependencies,input:{draftId:string;goalId:string;text:string}):Promise<ApplicationResult<SeasonSetupDraft>>{const r=await load(deps,input.draftId);if(!r.ok)return r;if(!editable(r.value))return applicationFailure({code:"invalid_transition",message:"Confirmed or closed setup drafts are immutable."});if(!r.value.proposedGoals.some(x=>x.id===input.goalId))return notFound("Proposed goal",input.goalId);return save(deps,{...r.value,proposedGoals:r.value.proposedGoals.map(x=>x.id===input.goalId?{...x,text:input.text.trim()}:x),status:"draft",updatedAt:deps.clock.now()});}
export async function removeProposedGoal(deps:SeasonWorkflowDependencies,input:{draftId:string;goalId:string}):Promise<ApplicationResult<SeasonSetupDraft>>{const r=await load(deps,input.draftId);if(!r.ok)return r;if(!editable(r.value))return applicationFailure({code:"invalid_transition",message:"Confirmed or closed setup drafts are immutable."});return save(deps,{...r.value,proposedGoals:r.value.proposedGoals.filter(x=>x.id!==input.goalId),status:"draft",updatedAt:deps.clock.now()});}
export async function addProposedOutcome(deps:SeasonWorkflowDependencies,input:{draftId:string;goalId:string;text:string;targetValue?:number|boolean;unit?:string;source?:"user"|"assistant"}):Promise<ApplicationResult<SeasonSetupDraft>>{const r=await load(deps,input.draftId);if(!r.ok)return r;if(!editable(r.value))return applicationFailure({code:"invalid_transition",message:"Confirmed or closed setup drafts are immutable."});if(!r.value.proposedGoals.some(x=>x.id===input.goalId))return notFound("Proposed goal",input.goalId);const id=deps.ids.nextWorkflowItemId();return save(deps,{...r.value,proposedOutcomes:[...r.value.proposedOutcomes,{id,text:input.text.trim(),source:input.source??"user",...(input.targetValue!==undefined?{targetValue:input.targetValue}:{}),...(input.unit?{unit:input.unit}:{})}],proposedGoals:r.value.proposedGoals.map(x=>x.id===input.goalId?{...x,outcomeIds:[...x.outcomeIds,id]}:x),status:"draft",updatedAt:deps.clock.now()});}
export async function updateProposedOutcome(deps:SeasonWorkflowDependencies,input:{draftId:string;outcomeId:string;text:string;targetValue?:number|boolean;unit?:string}):Promise<ApplicationResult<SeasonSetupDraft>>{const r=await load(deps,input.draftId);if(!r.ok)return r;if(!editable(r.value))return applicationFailure({code:"invalid_transition",message:"Confirmed or closed setup drafts are immutable."});if(!r.value.proposedOutcomes.some(x=>x.id===input.outcomeId))return notFound("Proposed outcome",input.outcomeId);return save(deps,{...r.value,proposedOutcomes:r.value.proposedOutcomes.map(x=>x.id===input.outcomeId?{...x,text:input.text.trim(),targetValue:input.targetValue,unit:input.unit}:x),status:"draft",updatedAt:deps.clock.now()});}
export async function removeProposedOutcome(deps:SeasonWorkflowDependencies,input:{draftId:string;outcomeId:string}):Promise<ApplicationResult<SeasonSetupDraft>>{const r=await load(deps,input.draftId);if(!r.ok)return r;if(!editable(r.value))return applicationFailure({code:"invalid_transition",message:"Confirmed or closed setup drafts are immutable."});return save(deps,{...r.value,proposedOutcomes:r.value.proposedOutcomes.filter(x=>x.id!==input.outcomeId),proposedGoals:r.value.proposedGoals.map(x=>({...x,outcomeIds:x.outcomeIds.filter(id=>id!==input.outcomeId)})),status:"draft",updatedAt:deps.clock.now()});}
export async function updateSetupItem(deps:SeasonWorkflowDependencies,input:{draftId:string;collection:"priorityIdeas"|"constraints"|"openQuestions";itemId:string;text:string}):Promise<ApplicationResult<SeasonSetupDraft>>{const r=await load(deps,input.draftId);if(!r.ok)return r;if(!editable(r.value))return applicationFailure({code:"invalid_transition",message:"Confirmed or closed setup drafts are immutable."});return save(deps,{...r.value,[input.collection]:r.value[input.collection].map(x=>x.id===input.itemId?{...x,text:input.text.trim()}:x),status:"draft",updatedAt:deps.clock.now()});}
export async function removeSetupItem(deps:SeasonWorkflowDependencies,input:{draftId:string;collection:"priorityIdeas"|"constraints"|"openQuestions";itemId:string}):Promise<ApplicationResult<SeasonSetupDraft>>{const r=await load(deps,input.draftId);if(!r.ok)return r;if(!editable(r.value))return applicationFailure({code:"invalid_transition",message:"Confirmed or closed setup drafts are immutable."});return save(deps,{...r.value,[input.collection]:r.value[input.collection].filter(x=>x.id!==input.itemId),status:"draft",updatedAt:deps.clock.now()});}
export async function applySetupSuggestion(deps:SeasonWorkflowDependencies,input:{draftId:string;suggestion:SeasonSetupSuggestion;priorityIds:string[];goalIds:string[]}):Promise<ApplicationResult<SeasonSetupDraft>>{const r=await load(deps,input.draftId);if(!r.ok)return r;if(!editable(r.value))return applicationFailure({code:"invalid_transition",message:"Confirmed or closed setup drafts are immutable."});const ps=input.suggestion.priorityIdeas.filter(x=>input.priorityIds.includes(x.id)).map(x=>({id:deps.ids.nextWorkflowItemId(),text:x.text,source:"assistant" as const}));const gs=input.suggestion.proposedGoals.filter(x=>input.goalIds.includes(x.id)).map(x=>({id:deps.ids.nextWorkflowItemId(),text:x.text,source:"assistant" as const,outcomeIds:[]}));return save(deps,{...r.value,priorityIdeas:[...r.value.priorityIdeas,...ps],proposedGoals:[...r.value.proposedGoals,...gs],status:"draft",updatedAt:deps.clock.now()});}
export async function markSetupReadyForReview(deps:SeasonWorkflowDependencies,draftId:string):Promise<ApplicationResult<SeasonSetupDraft>>{const r=await load(deps,draftId);if(!r.ok)return r;if(!editable(r.value))return applicationFailure({code:"invalid_transition",message:"Setup draft cannot enter review."});return save(deps,{...r.value,status:"ready_for_review",updatedAt:deps.clock.now()});}
export async function confirmSeasonSetup(deps:SeasonWorkflowDependencies,draftId:string):Promise<ApplicationResult<{draft:SeasonSetupDraft;readiness:ReturnType<typeof evaluateSetupReadiness>}>>{const r=await load(deps,draftId);if(!r.ok)return r;if(r.value.status!=="ready_for_review")return applicationFailure({code:"invalid_transition",message:"Setup must be ready for review before confirmation."});const readiness=evaluateSetupReadiness(r.value);if(!readiness.ready)return applicationFailure(...readiness.blockers.map(x=>({code:"validation_failed" as const,message:x.message,field:x.field})));const s=await save(deps,{...r.value,status:"confirmed",confirmedAt:deps.clock.now(),updatedAt:deps.clock.now()});return s.ok?applicationSuccess({draft:s.value,readiness}):s;}
export function createSeasonSetupConversionPlan(draft:SeasonSetupDraft):ApplicationResult<SeasonSetupConversionPlan>{if(draft.status!=="confirmed")return applicationFailure({code:"invalid_transition",message:"Only confirmed setup drafts can produce conversion plans."});const readiness=evaluateSetupReadiness(draft);if(!readiness.ready)return applicationFailure({code:"validation_failed",message:"Confirmed setup is structurally incomplete."});return applicationSuccess({draftId:draft.id,season:{title:draft.title,startDate:draft.startDate!,endDate:draft.endDate!},goals:draft.proposedGoals.map(x=>({proposalId:x.id,title:x.text,outcomeProposalIds:x.outcomeIds})),outcomes:draft.proposedOutcomes.map(x=>({proposalId:x.id,title:x.text,...(typeof x.targetValue==="number"?{targetValue:x.targetValue}:{}),...(x.unit?{unit:x.unit}:{})})),milestones:draft.supportingStructures.filter(x=>x.kind==="milestone").map(x=>({proposalId:x.id,title:x.text,...(x.proposedGoalId?{goalProposalId:x.proposedGoalId}:{}),...(x.dueDate?{dueDate:x.dueDate}:{})})),unsupportedStructures:draft.supportingStructures.filter(x=>x.kind!=="milestone")});}
