import { asc, eq, sql } from "drizzle-orm";
import type { SeasonReview, SeasonSetupDraft } from "../../domain";
import type { SeasonId, SeasonReviewId, SeasonSetupDraftId } from "../../domain/shared";
import type { KeepUpDatabase } from "../../database";
import { seasonReviews, seasonSetupDrafts } from "../../database/schema";
import type { SeasonReviewRepository, SeasonSetupDraftRepository, WorkflowRepositories } from "../contracts";
import { persistenceSuccess } from "../errors";
import { databaseFailure, normalizeTimestamps } from "./shared";
import { validateInsights, validateReviewProposal, validateReviewUserContent, validateSetupContent } from "./workflow-validation";
const clone=<T>(v:T):T=>structuredClone(v);
function setupFromRow(raw:typeof seasonSetupDrafts.$inferSelect){const r=normalizeTimestamps(raw);const content=validateSetupContent(r.content);if(!content.ok)return content;return persistenceSuccess<SeasonSetupDraft>({...content.value,id:r.id,status:r.status,createdAt:r.createdAt,updatedAt:r.updatedAt,...(r.confirmedAt?{confirmedAt:r.confirmedAt}:{}),...(r.convertedAt?{convertedAt:r.convertedAt}:{}),...(r.targetSeasonId?{targetSeasonId:r.targetSeasonId}:{})});}
function reviewFromRow(raw:typeof seasonReviews.$inferSelect){const r=normalizeTimestamps(raw);const user=validateReviewUserContent(r.userContent),insights=validateInsights(r.approvedCarryForwardInsights),proposal=r.assistantProposal===null?null:validateReviewProposal(r.assistantProposal);if(!user.ok)return user;if(!insights.ok)return insights;if(proposal&&!proposal.ok)return proposal;return persistenceSuccess<SeasonReview>({id:r.id,seasonId:r.seasonId,status:r.status,userContent:user.value,approvedCarryForwardInsights:insights.value,createdAt:r.createdAt,updatedAt:r.updatedAt,...(proposal?{assistantProposal:proposal.value}:{}),...(r.approvedSummary?{approvedSummary:r.approvedSummary}:{}),...(r.finalizedAt?{finalizedAt:r.finalizedAt}:{})});}
export class PostgresSeasonSetupDraftRepository implements SeasonSetupDraftRepository {constructor(private readonly db:KeepUpDatabase){} async findById(id:SeasonSetupDraftId){try{const [r]=await this.db.select().from(seasonSetupDrafts).where(eq(seasonSetupDrafts.id,id)).limit(1);return r?setupFromRow(r):persistenceSuccess(null);}catch(c){return databaseFailure("Setup draft lookup failed.",c);}} async list(){try{const rows=await this.db.select().from(seasonSetupDrafts).orderBy(asc(seasonSetupDrafts.createdAt),asc(seasonSetupDrafts.id));const values:SeasonSetupDraft[]=[];for(const r of rows){const x=setupFromRow(r);if(!x.ok)return x;values.push(x.value);}return persistenceSuccess(values);}catch(c){return databaseFailure("Setup draft listing failed.",c);}} async save(v:SeasonSetupDraft){try{const {id,status,createdAt,updatedAt,confirmedAt,convertedAt,targetSeasonId,...content}=clone(v);const row={id,status,createdAt,updatedAt,confirmedAt:confirmedAt??null,convertedAt:convertedAt??null,targetSeasonId:targetSeasonId??null,content};const [saved]=await this.db.insert(seasonSetupDrafts).values(row).onConflictDoUpdate({target:seasonSetupDrafts.id,set:row}).returning();return setupFromRow(saved!);}catch(c){return databaseFailure("Setup draft save failed.",c);}}}
export class PostgresSeasonReviewRepository implements SeasonReviewRepository {constructor(private readonly db:KeepUpDatabase){} async findById(id:SeasonReviewId){try{const [r]=await this.db.select().from(seasonReviews).where(eq(seasonReviews.id,id)).limit(1);return r?reviewFromRow(r):persistenceSuccess(null);}catch(c){return databaseFailure("Season review lookup failed.",c);}} async findBySeasonId(id:SeasonId){try{const [r]=await this.db.select().from(seasonReviews).where(eq(seasonReviews.seasonId,id)).limit(1);return r?reviewFromRow(r):persistenceSuccess(null);}catch(c){return databaseFailure("Season review lookup failed.",c);}} async list(){try{const rows=await this.db.select().from(seasonReviews).orderBy(asc(seasonReviews.createdAt),asc(seasonReviews.id));const values:SeasonReview[]=[];for(const r of rows){const x=reviewFromRow(r);if(!x.ok)return x;values.push(x.value);}return persistenceSuccess(values);}catch(c){return databaseFailure("Season review listing failed.",c);}} async save(v:SeasonReview){try{const row={id:v.id,seasonId:v.seasonId,status:v.status,userContent:clone(v.userContent),assistantProposal:v.assistantProposal?clone(v.assistantProposal):null,approvedSummary:v.approvedSummary??null,approvedCarryForwardInsights:clone(v.approvedCarryForwardInsights),createdAt:v.createdAt,updatedAt:v.updatedAt,finalizedAt:v.finalizedAt??null};const [saved]=await this.db.insert(seasonReviews).values(row).onConflictDoUpdate({target:seasonReviews.id,set:row}).returning();return reviewFromRow(saved!);}catch(c){return databaseFailure("Season review save failed.",c);}}}
export class PostgresWorkflowRepositories implements WorkflowRepositories {readonly setupDrafts;readonly reviews;constructor(private readonly db:KeepUpDatabase){this.setupDrafts=new PostgresSeasonSetupDraftRepository(db);this.reviews=new PostgresSeasonReviewRepository(db);}async lockSetupDraft(id:SeasonSetupDraftId){try{await this.db.execute(sql`select id from season_setup_drafts where id=${id} for update`);return persistenceSuccess(undefined);}catch(c){return databaseFailure("Setup draft lock failed.",c);}}}
