import { asc, eq } from "drizzle-orm";
import type { Goal, Milestone, Outcome, Season } from "../../domain";
import type { GoalId, MilestoneId, OutcomeId, SeasonId } from "../../domain/shared";
import type { KeepUpDatabase } from "../../database";
import { goals, milestones, outcomes, seasons } from "../../database/schema";
import type { GoalRepository, MilestoneRepository, OutcomeRepository, PlanningUnitOfWork, SeasonRepository } from "../contracts";
import { persistenceSuccess } from "../errors";
import { toGoalDomain, toGoalRecord, toMilestoneDomain, toMilestoneRecord, toOutcomeDomain, toOutcomeRecord, toSeasonDomain, toSeasonRecord } from "../mapping";
import { databaseFailure, normalizeTimestamps } from "./shared";

export class PostgresSeasonRepository implements SeasonRepository { constructor(private readonly db:KeepUpDatabase){} async findById(id:SeasonId){try{const [r]=await this.db.select().from(seasons).where(eq(seasons.id,id)).limit(1);return r?toSeasonDomain(normalizeTimestamps(r)):persistenceSuccess(null);}catch(c){return databaseFailure("Season lookup failed.",c);}} async list(){try{const rows=await this.db.select().from(seasons).orderBy(asc(seasons.startDate),asc(seasons.id));const values:Season[]=[];for(const r of rows){const x=toSeasonDomain(normalizeTimestamps(r));if(!x.ok)return x;values.push(x.value);}return persistenceSuccess(values);}catch(c){return databaseFailure("Season listing failed.",c);}} async save(v:Season){try{const r={...toSeasonRecord(v),status:v.status};const [saved]=await this.db.insert(seasons).values(r).onConflictDoUpdate({target:seasons.id,set:r}).returning();return toSeasonDomain(normalizeTimestamps(saved!));}catch(c){return databaseFailure("Season save failed.",c);}} }
export class PostgresGoalRepository implements GoalRepository { constructor(private readonly db:KeepUpDatabase){} async findById(id:GoalId){try{const [r]=await this.db.select().from(goals).where(eq(goals.id,id)).limit(1);return r?toGoalDomain(normalizeTimestamps(r)):persistenceSuccess(null);}catch(c){return databaseFailure("Goal lookup failed.",c);}} async listBySeasonId(id:SeasonId){try{const rows=await this.db.select().from(goals).where(eq(goals.seasonId,id)).orderBy(asc(goals.createdAt),asc(goals.id));const values:Goal[]=[];for(const r of rows){const x=toGoalDomain(normalizeTimestamps(r));if(!x.ok)return x;values.push(x.value);}return persistenceSuccess(values);}catch(c){return databaseFailure("Goal listing failed.",c);}} async save(v:Goal){try{const r={...toGoalRecord(v),status:v.status};const [saved]=await this.db.insert(goals).values(r).onConflictDoUpdate({target:goals.id,set:r}).returning();return toGoalDomain(normalizeTimestamps(saved!));}catch(c){return databaseFailure("Goal save failed.",c);}} }
export class PostgresOutcomeRepository implements OutcomeRepository { constructor(private readonly db:KeepUpDatabase){} async findById(id:OutcomeId){try{const [r]=await this.db.select().from(outcomes).where(eq(outcomes.id,id)).limit(1);return r?toOutcomeDomain(normalizeTimestamps({...r,targetValue:r.targetValue===null?null:Number(r.targetValue),progressValue:r.progressValue===null?null:Number(r.progressValue)})):persistenceSuccess(null);}catch(c){return databaseFailure("Outcome lookup failed.",c);}} async listByGoalId(id:GoalId){try{const rows=await this.db.select().from(outcomes).where(eq(outcomes.goalId,id)).orderBy(asc(outcomes.id));const values:Outcome[]=[];for(const r of rows){const x=toOutcomeDomain(normalizeTimestamps({...r,targetValue:r.targetValue===null?null:Number(r.targetValue),progressValue:r.progressValue===null?null:Number(r.progressValue)}));if(!x.ok)return x;values.push(x.value);}return persistenceSuccess(values);}catch(c){return databaseFailure("Outcome listing failed.",c);}} async save(v:Outcome){try{const r=toOutcomeRecord(v);const values={...r,type:v.type,targetValue:r.targetValue===null?null:String(r.targetValue),progressValue:r.progressValue===null?null:String(r.progressValue)};const [saved]=await this.db.insert(outcomes).values(values).onConflictDoUpdate({target:outcomes.id,set:values}).returning();return toOutcomeDomain(normalizeTimestamps({...saved!,targetValue:saved!.targetValue===null?null:Number(saved!.targetValue),progressValue:saved!.progressValue===null?null:Number(saved!.progressValue)}));}catch(c){return databaseFailure("Outcome save failed.",c);}} }
export class PostgresMilestoneRepository implements MilestoneRepository { constructor(private readonly db:KeepUpDatabase){} async findById(id:MilestoneId){try{const [r]=await this.db.select().from(milestones).where(eq(milestones.id,id)).limit(1);return r?toMilestoneDomain(normalizeTimestamps(r)):persistenceSuccess(null);}catch(c){return databaseFailure("Milestone lookup failed.",c);}} async listByGoalId(id:GoalId){try{const rows=await this.db.select().from(milestones).where(eq(milestones.goalId,id)).orderBy(asc(milestones.id));const values:Milestone[]=[];for(const r of rows){const x=toMilestoneDomain(normalizeTimestamps(r));if(!x.ok)return x;values.push(x.value);}return persistenceSuccess(values);}catch(c){return databaseFailure("Milestone listing failed.",c);}} async save(v:Milestone){try{const r={...toMilestoneRecord(v),status:v.status};const [saved]=await this.db.insert(milestones).values(r).onConflictDoUpdate({target:milestones.id,set:r}).returning();return toMilestoneDomain(normalizeTimestamps(saved!));}catch(c){return databaseFailure("Milestone save failed.",c);}} }
export class PostgresPlanningUnitOfWork implements PlanningUnitOfWork {readonly seasons;readonly goals;readonly outcomes;readonly milestones;constructor(db:KeepUpDatabase){this.seasons=new PostgresSeasonRepository(db);this.goals=new PostgresGoalRepository(db);this.outcomes=new PostgresOutcomeRepository(db);this.milestones=new PostgresMilestoneRepository(db);}}
